services:
#  mongo:
#    image: mongo:6
#    restart: always
#    volumes:
#      - mongo-data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: examplepassword

  api:
    build: .
    image: my-fastapi-mvc:latest
#    depends_on:
#      - mongo
    ports:
      - "8000:80"
    environment:
      MONGO_USER: #####
      MONGO_PASSWORD: ####
      MONGO_DB: test
